package DataObjects;
/*
 
* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;

/**
 *
 * @author shubh
 */
public class Adminpage extends javax.swing.JFrame {

    /**
     * Creates new form Adminpage
     */
    public Adminpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cobjectb = new javax.swing.JButton();
        cuserb = new javax.swing.JButton();
        logoutb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setText("Welcome Admin");

        cobjectb.setBackground(new java.awt.Color(102, 102, 255));
        cobjectb.setForeground(new java.awt.Color(255, 255, 255));
        cobjectb.setText("Create Object");
        cobjectb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobjectbActionPerformed(evt);
            }
        });

        cuserb.setBackground(new java.awt.Color(102, 102, 255));
        cuserb.setForeground(new java.awt.Color(255, 255, 255));
        cuserb.setText("Create User");
        cuserb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuserbActionPerformed(evt);
            }
        });

        logoutb.setBackground(new java.awt.Color(0, 255, 0));
        logoutb.setFont(new java.awt.Font("Euphemia UCAS", 1, 18)); // NOI18N
        logoutb.setForeground(new java.awt.Color(255, 255, 255));
        logoutb.setText("Log Out");
        logoutb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cobjectb, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuserb, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(logoutb)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(cuserb)
                .addGap(26, 26, 26)
                .addComponent(cobjectb)
                .addGap(18, 18, 18)
                .addComponent(logoutb)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cobjectbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobjectbActionPerformed
        // TODO add your handling code here:
    	JOptionPane.showMessageDialog(this,"object  established");
    	//createObject cu=new createObject();
    	createObject cu=new createObject();
    	//ab.setVisible(true);
    	
    	cu.maing();
    	this.setVisible(false);
    	
    }//GEN-LAST:event_cobjectbActionPerformed

    private void cuserbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuserbActionPerformed
        // TODO add your handling code here:
    	JOptionPane.showMessageDialog(this,"user  established");
    	this.setVisible(false);
    	createUser cu=new createUser();
    	//ab.setVisible(true);
    	
    	cu.maing();
    }//GEN-LAST:event_cuserbActionPerformed

    private void logoutbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbActionPerformed
        // TODO add your handling code here:
    	
    	JOptionPane.showMessageDialog(this,"logout established");
    	this.setVisible(false);
    }//GEN-LAST:event_logoutbActionPerformed

    /**
     * @param args the command line arguments
     */
    public void maing() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	Adminpage ab=new Adminpage();
                ab.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cobjectb;
    private javax.swing.JButton cuserb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutb;
    // End of variables declaration//GEN-END:variables
}
