package DataObjects;
/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;


import javax.swing.JOptionPane;

/**
 *
 * @author shubh
 */
public class changePassword extends javax.swing.JFrame {

    /**
     * Creates new form changePassword
     */
	
	String ud,pd2;
    public changePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        oldpasst = new javax.swing.JTextField();
        repeatnewpasst = new javax.swing.JPasswordField();
        newpasst = new javax.swing.JPasswordField();
        submitb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel3.setText("Old Password:");

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel4.setText("New Password");

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel5.setText("Confirm New Password");

        oldpasst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpasstActionPerformed(evt);
            }
        });

        repeatnewpasst.setText("****");
        repeatnewpasst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                repeatnewpasstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                repeatnewpasstFocusLost(evt);
            }
        });
        repeatnewpasst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatnewpasstActionPerformed(evt);
            }
        });

        newpasst.setText("****");
        newpasst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newpasstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newpasstFocusLost(evt);
            }
        });
        newpasst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpasstActionPerformed(evt);
            }
        });

        submitb.setBackground(new java.awt.Color(102, 102, 255));
        submitb.setForeground(new java.awt.Color(255, 255, 255));
        submitb.setText("Submit");
        submitb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oldpasst)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(repeatnewpasst)
                    .addComponent(newpasst, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(submitb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(oldpasst, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(newpasst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(repeatnewpasst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setText("For Security Reasons ");

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel2.setText("You need to change your password ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oldpasstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpasstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpasstActionPerformed

    private void submitbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbActionPerformed
        // TODO add your handling code here:
    	
    	
    	
    	
    	System.out.println("objects are "+ud);
    	System.out.println("objects are "+pd2);
    	
    	String op="o";
    			op=oldpasst.getText();
    	String np="o";
    	np=newpasst.getText();
    	String rp="o";
    	rp=repeatnewpasst.getText();
    	newpasst.setText("");
    	repeatnewpasst.setText("");
    	oldpasst.setText("");
    	
    	
    	if(op.equals("o")||np.equals("o")||rp.equals("o"))
    	{
    		JOptionPane.showMessageDialog(this,"u fill all the fields");
    	}
    	if(pd2.equals(np)||pd2.equals(rp)){
    		JOptionPane.showMessageDialog(this,"u have given same password");
    	}
    	
    	else if(!(rp.equals(np)))
    	{
    		JOptionPane.showMessageDialog(this,"reentered passwords are not equal");
    	}
    	
    	else
    	{
    		
    		
    		try{
        		Connection Con= DbConnection.GetDbConnection();
        	
        		
        		Statement stmt = null;	 stmt = Con.createStatement();
        		
        		/* String sql = "update user_cred set pass='"+np+"' where sub_id='"+ud+"'";
        		 
        		 stmt = Con.createStatement();
        		 int p=stmt.executeUpdate(sql);
        		 System.out.println("p is"+p);*/
        		
        		String sql0 = "DELETE FROM user_cred where sub_id='"+ud+"'";
                
                stmt.executeUpdate(sql0);
                
                
                
                String sql9 = "INSERT INTO user_cred(sub_id,pass)VALUES (?,?)";
           	 
    	    	PreparedStatement statement90 = Con.prepareStatement(sql9);
    	    	 
    	    	 
    	        statement90.setString(1,ud);
    	    	statement90.setString(2,np);
    	    	 //statement1.setString(3,tpe);
    	    	 
    	    	  
    	    	int rowsInserted170 = statement90.executeUpdate();
    	    	 if (rowsInserted170 > 0) {
    	    	    System.out.println("A new user was inserted successfully in security level!");
    	    	     JOptionPane.showMessageDialog(this,"Thank u username and password! ");
    	    	 }
                
                
                
        		 
        		 
        		 
        		 
        		
        		
        		
        		
    		}catch(Exception e){
    			
    		}
    		
    		
    	}
    	
    				
    		
    	
    	
    	
    	
    	
    	
    	
    	
    	
    }//GEN-LAST:event_submitbActionPerformed

    private void repeatnewpasstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatnewpasstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repeatnewpasstActionPerformed

    private void newpasstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpasstActionPerformed

    private void newpasstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newpasstFocusGained
        // TODO add your handling code here:
        if(newpasst.getText().equals("****"))
        newpasst.setText("");
    }//GEN-LAST:event_newpasstFocusGained

    private void newpasstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newpasstFocusLost
        // TODO add your handling code here:
         if(newpasst.getText().equals(""))
        newpasst.setText("****");
        
    }//GEN-LAST:event_newpasstFocusLost

    private void repeatnewpasstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repeatnewpasstFocusGained
        // TODO add your handling code here:
        if(repeatnewpasst.getText().equals("****"))
        repeatnewpasst.setText("");
    }//GEN-LAST:event_repeatnewpasstFocusGained

    private void repeatnewpasstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repeatnewpasstFocusLost
        // TODO add your handling code here:
         if(repeatnewpasst.getText().equals(""))
        repeatnewpasst.setText("****");
        
    }//GEN-LAST:event_repeatnewpasstFocusLost

    /**
     * @param args the command line arguments
     */
    //public void para(String pd2,String )
    public void maing(String ud,String pd2) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	//this.ud=ud;
    	//this.pd2=pd2;
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	changePassword ss=new changePassword();
            	ss.ud=ud;
            	ss.pd2=pd2;
               ss.setVisible(true);
            	//.setPara(ud,pd2);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField newpasst;
    private javax.swing.JTextField oldpasst;
    private javax.swing.JPasswordField repeatnewpasst;
    private javax.swing.JButton submitb;
    // End of variables declaration//GEN-END:variables
}
