package DataObjects;
import java.sql.Connection;
import java.io.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubh
 */
public class createObject extends javax.swing.JFrame {

    /**
     * Creates new form createObject
     */
    public createObject() {
        initComponents();
        frame1.setFocusable(true);
        groupButton();
        
    }
    private void groupButton(){
    ButtonGroup bg2=new ButtonGroup();
    bg2.add(r2a);
    bg2.add(r2b);
    bg2.add(r2c);
    bg2.add(r2d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        frame1 = new javax.swing.JInternalFrame();
        objectt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        r2a = new javax.swing.JRadioButton();
        r2b = new javax.swing.JRadioButton();
        r2c = new javax.swing.JRadioButton();
        r2d = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frame1.setVisible(true);

        objectt.setText("Object name");
        objectt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                objecttFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                objecttFocusLost(evt);
            }
        });
        objectt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objecttActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel2.setText("Add Object");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel3.setText("Clearence :");

        r2a.setSelected(true);
        r2a.setText("Top Secret");
        r2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2aActionPerformed(evt);
            }
        });

        r2b.setText("Secret");
        r2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2bActionPerformed(evt);
            }
        });

        r2c.setText("Confidential");
        r2c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2cActionPerformed(evt);
            }
        });

        r2d.setText("Unclassified");
        r2d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2dActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel5.setText("Set :");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Nato");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Nuclear");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Navy");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame1Layout = new javax.swing.GroupLayout(frame1.getContentPane());
        frame1.getContentPane().setLayout(frame1Layout);
        frame1Layout.setHorizontalGroup(
            frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addContainerGap(248, Short.MAX_VALUE))
                    .addGroup(frame1Layout.createSequentialGroup()
                        .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(frame1Layout.createSequentialGroup()
                                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r2c)
                                    .addComponent(r2a))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r2b)
                                    .addComponent(r2d)
                                    .addComponent(jCheckBox2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frame1Layout.createSequentialGroup()
                                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(objectt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(29, 29, 29))))
        );
        frame1Layout.setVerticalGroup(
            frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(objectt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r2a)
                    .addComponent(r2b))
                .addGap(18, 18, 18)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r2c)
                    .addComponent(r2d))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(76, 76, 76))
        );

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setText("Welcome Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(frame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(frame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void objecttActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void r2aActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void r2bActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void r2cActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void r2dActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	
    	
    	
    	JOptionPane.showMessageDialog(this,"Jbutton testing");
    	
int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0;
    	String cle="o",cle1="o",cle2="o",cle3="o";
    	JOptionPane.showMessageDialog(this,"Jbutton established");
    	if(r2a.isSelected()){
    	r1=1;
    	cle="topsecret";
    	JOptionPane.showMessageDialog(null, "r1 selected");
    	}
    	
    	if(r2b.isSelected()){
    		r2=1;
    		cle="secret";
    		JOptionPane.showMessageDialog(null, "r2 selected");
    	}
    	
    	if(r2c.isSelected()){
    		r3=1;
    		cle="confidential";
    		JOptionPane.showMessageDialog(null, "r3 selected");
    	}
    	
    	if(r2d.isSelected()){
    		cle="unclassified";
    		r4=1;
    		JOptionPane.showMessageDialog(null, "r4 selected");
    	}
    	
    	System.out.println("r1 status is "+r1+"r2 status is "+r2+"r3 status is "+r3+"r4 status is "+r4);
    	
    	if(jCheckBox1.isSelected()){
    		r5=1;
    		JOptionPane.showMessageDialog(null, "r5 selected");
    		cle1="nato";
    	}
    	
    	if(jCheckBox2.isSelected()){
    		r6=1;
    		JOptionPane.showMessageDialog(null, "r6 selected");
    		cle2="nuclear";
    	}
    	
    	if(jCheckBox3.isSelected()){
    		r7=1;
    		cle3="navy";
    		JOptionPane.showMessageDialog(null, "r7 selected");
    	}
    	//JOptionPane.showMessageDialog(null, "you have entered" + + "names");
    	//if(jCheckBox4.isSelected())
    		//r8=1;
    	
    	//String cle="o",cle1="o",cle2="o",cle3="o";
    	/*if(r1==1)
    		cle="topsecret";
    	
    	if(r2==1)
    		cle="secret";
    	if(r3==1)
    		cle="confidential";
    	if(r4==1)
    		cle="unclassified";*/
    	
    	String us=objectt.getText();
    	us=us+".txt";
    	JOptionPane.showMessageDialog(null, "u typed "+us);
    	System.out.println("category status is "+cle1);
    	System.out.println("category status is "+cle2);
    	System.out.println("category status is "+cle3);
    	JOptionPane.showMessageDialog(null, "u selected"+cle1);
    	JOptionPane.showMessageDialog(null, "u selected"+cle2);
    	JOptionPane.showMessageDialog(null, "u selected"+cle3);
    	System.out.println("r5 status is "+r5+"r6 status is "+r6+"r7 status is "+r7);
    	
    	
    	
    	
    	
    	try{
    		Connection Con= DbConnection.GetDbConnection();
    	
    		
    		Statement stmt = null;	 stmt = Con.createStatement();
    		
    		//Statement stmt = null;	 stmt = Con.createStatement();
    		
    		
    		
    		String uincr="o",pincr="o",oincr="o";
    		int uincr1=0,pincr1=0;
    		JOptionPane.showMessageDialog(this,"bfore select");
    		
    		 String sql = "SELECT subid,pwd,obid FROM incr1";
    		 JOptionPane.showMessageDialog(this,"enter in to else part");
    		 
             ResultSet rs = stmt.executeQuery(sql);
             JOptionPane.showMessageDialog(this,"after result set");
             //STEP 5: Extract data from result set
            // String ud;
             //String pd2="i";
             while(rs.next()){
                //Retrieve by column name
            	  uincr  = rs.getString("subid");
                  pincr = rs.getString("pwd");
                  oincr = rs.getString("obid");
               uincr1=Integer.parseInt(oincr);
               // pincr1=Integer.parseInt(pincr);

                //Display values
                System.out.println("useridincr1: " + uincr1);
                System.out.println("passwdincr1: " + pincr1);
                
                
             }
           
             
            if(uincr1==0)
            	 
             {
             
             JOptionPane.showMessageDialog(this,"set increement values correctly in database");
             }
             
             
             
             if(uincr1==0 || oincr.equals("o"))
             {
            	 JOptionPane.showMessageDialog(this,"not recorded in database counter");
             }
             
           
            else{
            	  uincr1++;
                  //pincr1++;
            	 JOptionPane.showMessageDialog(this,"enter in to else part");
            	 String db=Integer.toString(uincr1);
            	// String pdb=Integer.toString(pincr1);
             
             String udd="obj"+uincr1;
             //String pdd="pwd"+pincr1;
             System.out.println("useridincr string usr: " + udd);
             //System.out.println("passwdincr string prefix pwd: " + pdd);
             
             
            
             String sql0 = "DELETE FROM incr1";
                          
             stmt.executeUpdate(sql0);
             
             
             
          String sql31 = "INSERT INTO incr1(subid,pwd,obid)VALUES (?,?,?)";
	    	 
 	    	PreparedStatement statement31 = Con.prepareStatement(sql31);
 	    	 
 	    	 
 	    statement31.setString(1,uincr);
 	    	statement31.setString(2,pincr);
 	    	 statement31.setString(3,db);
 	    	 
 	    	  
 	   int rowsInserted1 = statement31.executeUpdate();
 	    	if (rowsInserted1 > 0) {
 	    	   System.out.println("value incremented successfully!");
 	    	     JOptionPane.showMessageDialog(this,"Thank u! ");
 	    	 }
            
             
             
 	    	 
 	    	
 	    	
 	    	
 	    	if(r1==1||r2==1||r3==1||r4==1){
 	       	
 	    		String sql3 = "INSERT INTO object_clearence(obj_id,obj_name,obj_seclevel)VALUES (?,?,?)";
 		    	 
 		    	PreparedStatement statement1 = Con.prepareStatement(sql3);
 		    	//if(r1==1)
 		    		
 		    	 
 		    	 
 		    statement1.setString(1,udd);
 		    	statement1.setString(2,us);
 		    	 statement1.setString(3,cle);
 		    	 
 		    	  
 		    	 int rowsInserted13 = statement1.executeUpdate();
 		    	 if (rowsInserted13 > 0) {
 		    	    System.out.println("A new user was inserted successfully in security level!"+cle);
 		    	     JOptionPane.showMessageDialog(this,"Thank u! ");
 		    	 }
 		    	     
 		    	     
 		    	     
 		    	     
 	    		
 	    		
 	    	}
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	if(r5==1){
 	        	
 	    		 String sql4 = "INSERT INTO obj_cat(obj_id,obj_category)VALUES (?,?)";
 		    	 
 		    	PreparedStatement statement2 = Con.prepareStatement(sql4);
 		    	 
 		    	 //String dj="nato";
 		        statement2.setString(1,udd);
 		    	statement2.setString(2,cle1);
 		    	 //statement1.setString(3,tpe);
 		    	 
 		    	  
 		    	 int rowsInserted14 = statement2.executeUpdate();
 		    	 if (rowsInserted14 > 0) {
 		    	     System.out.println("A new user was inserted successfully in security level!");
 		    	     JOptionPane.showMessageDialog(this,"Thank u! ");
 		    	 }
 		    	     
 		    	     
 		    	     
 		    	     
 	    		
 	    		
 	    	}
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	if(r6==1){
 	        	
 	   		 String sql5 = "INSERT INTO obj_cat(obj_id,obj_category)VALUES (?,?)";
 		    	 
 		    	PreparedStatement statement3 = Con.prepareStatement(sql5);
 		    	 
 		    	 
 		        statement3.setString(1,udd);
 		    	statement3.setString(2,cle2);
 		    	 //statement1.setString(3,tpe);
 		    	 
 		    	  
 		    	int rowsInserted16 = statement3.executeUpdate();
 		    	if(rowsInserted16 > 0) {
 		    	    System.out.println("A new user was nuclear inserted successfully in security level!");
 		    	     JOptionPane.showMessageDialog(this," nuclear Thank u! ");
 		    	 }
 		    	     
 		    	     
 		    	     
 		    	     
 	   		
 	   		
 	   	}
 	    	
 	    	
 	    	
 	    	
 	    	if(r7==1){
 	        	
 	   		 String sql6 = "INSERT INTO obj_cat(obj_id,obj_category)VALUES (?,?)";
 		    	 
 		    	PreparedStatement statement4 = Con.prepareStatement(sql6);
 		    	 
 		    	 
 		        statement4.setString(1,udd);
 		    	statement4.setString(2,cle3);
 		    	 //statement1.setString(3,tpe);
 		    	 
 		    	  
 		    	int rowsInserted17 = statement4.executeUpdate();
 		    	 if (rowsInserted17 > 0) {
 		    	    System.out.println("A new user was inserted successfully in security level!");
 		    	     JOptionPane.showMessageDialog(this,"Thank u navy! ");
 		    	 }
 		    	     
 		    	     
 		    	     
 		    	     
 	   		
 	   		
 	   	}
 	    	
 	    	
 	    	
 	    	
 	    	try {

 	   		String filename = us;
 	   		String workingDirectory = System.getProperty("user.dir");
 	   			
 	   		//****************//
 	   			
 	   		String absoluteFilePath = "";
 	   			
 	   		//absoluteFilePath = workingDirectory + System.getProperty("file.separator") + filename;
 	   		absoluteFilePath = workingDirectory + File.separator +"src/DataObjects/"+ filename;
 	   	//absoluteFilePath=absoluteFilePath+"\D:\JavaProject\MAC2\src\DataObjects\"

 	   		System.out.println("Final filepath : " + absoluteFilePath);
 	   			
 	   		//****************//
 	   			
 	   		File file = new File(absoluteFilePath);

 	   		if (file.createNewFile()) {
 	   			System.out.println("File is created!");
 	   		JOptionPane.showMessageDialog(null, "file is created " );
 	   		} else {
 	   			System.out.println("File is already existed!");
 	   		JOptionPane.showMessageDialog(null, "file already exists "); 
 	   			
 	   		}

 	   	  } catch (IOException e) {
 	   		e.printStackTrace();
 	   	  }
 	    	
 	    	
 	    	//udd - obj id
 	    	//us-obj name
 	    	//String path="D:/JavaProject/MAC2/src/DataObjects"+us;
 	    	//File file=new File(path);
 	    	
 	    	JOptionPane.showMessageDialog(null, "object name is " +udd + "object name is "+us);
 	    	
 	    	
 	    	//objectCreatedMessage oc=new objectCreatedMessage();
 			//oc.maing(udd,us);
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	//end of incr1 but else bracket is not here
            }
    		
    		
    		
    		
    		
    		
    		
    		
    		
    		
    		
    		
    		
    		
    		
    		
    		
    		
    		
    
    	
    		
    		
    		
    		
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	JOptionPane.showMessageDialog(null, "u selected classification is "+cle);
    	Con.close();	
    	}catch(Exception e){
    		
    		
    	}	
        
    }                                        

    private void objecttFocusGained(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
        if(objectt.getText().equals("Object name"))
        objectt.setText("");
    }                                   

    private void objecttFocusLost(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
        if(objectt.getText().equals(""))
        objectt.setText("Object name");
    }                                 

    /**
     * @param args the command line arguments
     */
    public static void maing() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createObject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createObject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JInternalFrame frame1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField objectt;
    private javax.swing.JRadioButton r2a;
    private javax.swing.JRadioButton r2b;
    private javax.swing.JRadioButton r2c;
    private javax.swing.JRadioButton r2d;
    // End of variables declaration                   
}
