package DataObjects;
import java.sql.Connection;
import java.io.*;
import java.util.*;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubh
 */
public class createUser extends javax.swing.JFrame {

    /**
     * Creates new form createUser
     */
    public createUser() {
        initComponents();
        frame1.setFocusable(true);
        groupButton();
        
    }
    private void groupButton(){
    ButtonGroup bg2=new ButtonGroup();
    bg2.add(r2a);
    bg2.add(r2b);
    bg2.add(r2c);
    bg2.add(r2d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        frame1 = new javax.swing.JInternalFrame();
        usert = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        r2a = new javax.swing.JRadioButton();
        r2b = new javax.swing.JRadioButton();
        r2c = new javax.swing.JRadioButton();
        r2d = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frame1.setVisible(true);

        usert.setText("User Name");
        usert.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usertFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usertFocusLost(evt);
            }
        });
        usert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel2.setText("Add User");

        passt.setText("Password");
        passt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passtFocusLost(evt);
            }
        });
        passt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel3.setText("Clearence :");

        r2a.setSelected(true);
        r2a.setText("Top Secret");
        r2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2aActionPerformed(evt);
            }
        });

        r2b.setText("Secret");
        r2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2bActionPerformed(evt);
            }
        });

        r2c.setText("Confidential");
        r2c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2cActionPerformed(evt);
            }
        });

        r2d.setText("Unclassified");
        r2d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2dActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel5.setText("Set :");

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Nato");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Nuclear");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Navy");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame1Layout = new javax.swing.GroupLayout(frame1.getContentPane());
        frame1.getContentPane().setLayout(frame1Layout);
        frame1Layout.setHorizontalGroup(
            frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame1Layout.createSequentialGroup()
                        .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frame1Layout.createSequentialGroup()
                                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r2c)
                                    .addComponent(r2a))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r2b)
                                    .addComponent(r2d))))
                        .addGap(29, 29, 29))
                    .addGroup(frame1Layout.createSequentialGroup()
                        .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox3)
                            .addGroup(frame1Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(90, 90, 90)
                                .addComponent(jCheckBox2))
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(usert, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(passt))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        frame1Layout.setVerticalGroup(
            frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(usert, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(passt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r2a)
                    .addComponent(r2b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r2d)
                    .addComponent(r2c))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel1.setText("Welcome Admin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(frame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(frame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertActionPerformed

    private void passtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtActionPerformed

    private void r2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2aActionPerformed

    private void r2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2bActionPerformed

    private void r2cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2cActionPerformed

    private void r2dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2dActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) //throws IOException
    {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	
    	
    	int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0;
    	
    	JOptionPane.showMessageDialog(this,"Jbutton established");
    	if(r2a.isSelected()){
    	r1=1;
    	JOptionPane.showMessageDialog(null, "r1 selected");
    	}
    	
    	if(r2b.isSelected()){
    		r2=1;
    		JOptionPane.showMessageDialog(null, "r2 selected");
    	}
    	
    	if(r2c.isSelected()){
    		r3=1;
    		JOptionPane.showMessageDialog(null, "r3 selected");
    	}
    	
    	if(r2d.isSelected()){
    		r4=1;
    		JOptionPane.showMessageDialog(null, "r4 selected");
    	}
    	
    	System.out.println("r1 status is "+r1+"r2 status is "+r2+"r3 status is "+r3+"r4 status is "+r4);
    	
    	if(jCheckBox1.isSelected()){
    		r5=1;
    		JOptionPane.showMessageDialog(null, "r5 selected");
    	}
    	
    	if(jCheckBox2.isSelected()){
    		r6=1;
    		JOptionPane.showMessageDialog(null, "r6 selected");
    	}
    	
    	if(jCheckBox3.isSelected()){
    		r7=1;
    		JOptionPane.showMessageDialog(null, "r7 selected");
    	}
    	//JOptionPane.showMessageDialog(null, "you have entered" + + "names");
    	//if(jCheckBox4.isSelected())
    		//r8=1;
    	String cle="o",cle1="o",cle2="o",cle3="o";
    	if(r1==1)
    		cle="topsecret";
    	
    	if(r2==1)
    		cle="secret";
    	if(r3==1)
    		cle="confidential";
    	if(r4==1)
    		cle="unclassified";
    	
    	
    	
    	JOptionPane.showMessageDialog(null, "u selected classification is "+cle);
    	
    	
    	
    	
       
//int usrid=0,pasid=0;
//String fileName = "initfile.txt",update;

JOptionPane.showMessageDialog(this,"tej code enter");

/*try{
	JOptionPane.showMessageDialog(this,"tej code enter try");
FileReader fileReader = new FileReader(fileName);
BufferedReader br = new BufferedReader(fileReader);

StringTokenizer st = new StringTokenizer(br.readLine());

usrid= Integer.parseInt(st.nextToken());
pasid= Integer.parseInt(st.nextToken());
//objid= Integer.parseInt(st.nextToken());
usrid++;
pasid++;
System.out.println("usrincr inside status is "+usrid);
System.out.println("pwdincr status inside is "+pasid);
JOptionPane.showMessageDialog(this,"tej code enterafter incr");
br.close();
fileReader.close();
FileWriter fileWriter = new FileWriter(fileName);
BufferedWriter bw = new BufferedWriter(fileWriter);
update=Integer.toString(usrid)+" "+Integer.toString(pasid);
bw.write(update);
bw.close();
fileWriter.close();
}
catch(IOException e)
{
	JOptionPane.showMessageDialog(this,"tej cod exit catch");
	}*/









    	
    	
    	
    	
    	



    	
    	System.out.println("clearence status is "+cle);
    	
    	
    	if(r5==1)
    		cle1="nato";
    	
    	if(r6==1)
    		cle2="nuclear";
    	if(r7==1)
    		cle3="navy";
    	
    	System.out.println("category status is "+cle1);
    	System.out.println("category status is "+cle2);
    	System.out.println("category status is "+cle3);
    	
    	
    	
    	String us=usert.getText();
    	//passt.setText("bala");
    	
    	
    try{
    		Connection Con= DbConnection.GetDbConnection();
    	
    		
    		Statement stmt = null;	 stmt = Con.createStatement();

    		String uincr="o",pincr="o",oincr="o";
    		int uincr1=0,pincr1=0;
    		JOptionPane.showMessageDialog(this,"bfore select");
    		
    		 String sql = "SELECT subid,pwd,obid FROM incr1";
    		 JOptionPane.showMessageDialog(this,"enter in to else part");
    		 
             ResultSet rs = stmt.executeQuery(sql);
             JOptionPane.showMessageDialog(this,"after result set");
             //STEP 5: Extract data from result set
            // String ud;
             //String pd2="i";
             while(rs.next()){
                //Retrieve by column name
            	  uincr  = rs.getString("subid");
                  pincr = rs.getString("pwd");
                  oincr = rs.getString("obid");
               uincr1=Integer.parseInt(uincr);
                pincr1=Integer.parseInt(pincr);

                //Display values
                System.out.println("useridincr1: " + uincr1);
                System.out.println("passwdincr1: " + pincr1);
                
                
             }
           
             
            if(uincr1==0&&pincr1==0)
            	 
             {
             
             JOptionPane.showMessageDialog(this,"set increement values correctly in database");
             }
             
             
             
             if(uincr1==0 || pincr1==0 || uincr.equals("o")||pincr.equals("o") )
             {
            	 JOptionPane.showMessageDialog(this,"not recorded in database counter");
             }
             
           
            else{
            	  uincr1++;
                  pincr1++;
            	 JOptionPane.showMessageDialog(this,"enter in to else part");
            	 String db=Integer.toString(uincr1);
            	 String pdb=Integer.toString(pincr1);
             
             String udd="usr"+uincr1;
             String pdd="pwd"+pincr1;
             System.out.println("useridincr string usr: " + udd);
             System.out.println("passwdincr string prefix pwd: " + pdd);
             
            
             String sql0 = "DELETE FROM incr1";
                          
             stmt.executeUpdate(sql0);
             
             
             
          String sql31 = "INSERT INTO incr1(subid,pwd,obid)VALUES (?,?,?)";
	    	 
 	    	PreparedStatement statement31 = Con.prepareStatement(sql31);
 	    	 
 	    	 
 	    statement31.setString(1,db);
 	    	statement31.setString(2,pdb);
 	    	 statement31.setString(3,oincr);
 	    	 
 	    	  
 	   int rowsInserted1 = statement31.executeUpdate();
 	    	if (rowsInserted1 > 0) {
 	    	   System.out.println("A new user was inserted successfully in security level!");
 	    	     JOptionPane.showMessageDialog(this,"Thank u! ");
 	    	 }
            
             
             
 	    	 
 	    	
 	    	
 	    	//end of incr1 but else bracket is not here
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
 	    	
             
             
             
             
    		
    		
    		
    	if(r1==1||r2==1||r3==1||r4==1){
    	
    		String sql3 = "INSERT INTO subject_clearence(sub_id,sub_name,sub_sec_level)VALUES (?,?,?)";
	    	 
	    	PreparedStatement statement1 = Con.prepareStatement(sql3);
	    	//if(r1==1)
	    		
	    	 
	    	 
	    statement1.setString(1,udd);
	    	statement1.setString(2,us);
	    	 statement1.setString(3,cle);
	    	 
	    	  
	    	 int rowsInserted13 = statement1.executeUpdate();
	    	 if (rowsInserted13 > 0) {
	    	    System.out.println("A new user was inserted successfully in security level!"+cle);
	    	     JOptionPane.showMessageDialog(this,"Thank u! ");
	    	 }
	    	     
	    	     
	    	     
	    	     
    		
    		
    	}
    	
    	
    	if(r5==1){
        	
    		 String sql4 = "INSERT INTO sub_cat(sub_id,sub_category)VALUES (?,?)";
	    	 
	    	PreparedStatement statement2 = Con.prepareStatement(sql4);
	    	 
	    	 
	        statement2.setString(1,udd);
	    	statement2.setString(2,cle1);
	    	 //statement1.setString(3,tpe);
	    	 
	    	  
	    	 int rowsInserted14 = statement2.executeUpdate();
	    	 if (rowsInserted14 > 0) {
	    	     System.out.println("A new user was inserted successfully in security level!");
	    	     JOptionPane.showMessageDialog(this,"Thank u! ");
	    	 }
	    	     
	    	     
	    	     
	    	     
    		
    		
    	}
    	
    	
    	
    	
    	
    	if(r6==1){
        	
   		 String sql5 = "INSERT INTO sub_cat(sub_id,sub_category)VALUES (?,?)";
	    	 
	    	PreparedStatement statement3 = Con.prepareStatement(sql5);
	    	 
	    	 
	        statement3.setString(1,udd);
	    	statement3.setString(2,cle2);
	    	 //statement1.setString(3,tpe);
	    	 
	    	  
	    	int rowsInserted16 = statement3.executeUpdate();
	    	if(rowsInserted16 > 0) {
	    	    System.out.println("A new user was nuclear inserted successfully in security level!");
	    	     JOptionPane.showMessageDialog(this," nuclear Thank u! ");
	    	 }
	    	     
	    	     
	    	     
	    	     
   		
   		
   	}
    	
    	
    	
    	
    	if(r7==1){
        	
   		 String sql6 = "INSERT INTO sub_cat(sub_id,sub_category)VALUES (?,?)";
	    	 
	    	PreparedStatement statement4 = Con.prepareStatement(sql6);
	    	 
	    	 
	        statement4.setString(1,udd);
	    	statement4.setString(2,cle3);
	    	 //statement1.setString(3,tpe);
	    	 
	    	  
	    	int rowsInserted17 = statement4.executeUpdate();
	    	 if (rowsInserted17 > 0) {
	    	    System.out.println("A new user was inserted successfully in security level!");
	    	     JOptionPane.showMessageDialog(this,"Thank u navy! ");
	    	 }
	    	     
	    	     
	    	     
	    	     
   		
   		
   	}
 	    	
 	    
    	JOptionPane.showMessageDialog(this,"enter user and password! ");
    	 String sql9 = "INSERT INTO user_cred(sub_id,pass)VALUES (?,?)";
    	 
	    	PreparedStatement statement90 = Con.prepareStatement(sql9);
	    	 
	    	 
	        statement90.setString(1,udd);
	    	statement90.setString(2,pdd);
	    	 //statement1.setString(3,tpe);
	    	 
	    	  
	    	int rowsInserted170 = statement90.executeUpdate();
	    	 if (rowsInserted170 > 0) {
	    	    System.out.println("A new user was inserted successfully in security level!");
	    	     JOptionPane.showMessageDialog(this,"Thank u username and password! ");
	    	 }
    	
    	
 	    	
 	    	
 	    	
 	    	passt.setText(pdd);
 	    	
 	    	
 	    	
 	    	 
 	       
    	
    	
    	
    	
    	
    	
           }//else end
    	
    	
    	
    	
    	
    	
    	
    	
    	
    	
    		
    		
    	
    	Con.close();
    	
    	}catch(Exception e){
    		
    		
    	}
    	
    	
    	
    	
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usertFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usertFocusGained
        // TODO add your handling code here:
        if(usert.getText().equals("User Name"))
        usert.setText("");
    }//GEN-LAST:event_usertFocusGained

    private void usertFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usertFocusLost
        // TODO add your handling code here:
        if(usert.getText().equals(""))
        usert.setText("User Name");
    }//GEN-LAST:event_usertFocusLost

    private void passtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passtFocusGained
        // TODO add your handling code here:
        if(passt.getText().equals("Password"))
        passt.setText("");
    }//GEN-LAST:event_passtFocusGained

    private void passtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passtFocusLost
        // TODO add your handling code here:
        if(passt.getText().equals(""))
        passt.setText("Password");
    }//GEN-LAST:event_passtFocusLost

    /**
     * @param args the command line arguments
     */
    public void maing() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JInternalFrame frame1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField passt;
    private javax.swing.JRadioButton r2a;
    private javax.swing.JRadioButton r2b;
    private javax.swing.JRadioButton r2c;
    private javax.swing.JRadioButton r2d;
    private javax.swing.JTextField usert;
    // End of variables declaration//GEN-END:variables
}
