package DataObjects;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.*;
import java.sql.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubh
 */
public class mains extends javax.swing.JFrame {

    /**
     * Creates new form mains
     */
    public mains() {
        initComponents();
        frame1.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame1 = new javax.swing.JInternalFrame();
        usernamet = new javax.swing.JTextField();
        loginb = new javax.swing.JButton();
        passwordt = new javax.swing.JPasswordField();
        showb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frame1.setBackground(new java.awt.Color(255, 255, 255));
        frame1.setVisible(true);

        usernamet.setText("User Name");
        usernamet.setToolTipText("");
        usernamet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernametFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernametFocusLost(evt);
            }
        });
        usernamet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametActionPerformed(evt);
            }
        });

        loginb.setBackground(new java.awt.Color(102, 102, 255));
        loginb.setForeground(new java.awt.Color(255, 255, 255));
        loginb.setText("Log In");
        loginb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbActionPerformed(evt);
            }
        });

        passwordt.setText("*****");
        passwordt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordtFocusLost(evt);
            }
        });
        passwordt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtActionPerformed(evt);
            }
        });

        showb.setText("Show");
        showb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("User Log In");

        jLabel2.setText("Are you admin ?");

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Admin Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame1Layout = new javax.swing.GroupLayout(frame1.getContentPane());
        frame1.getContentPane().setLayout(frame1Layout);
        frame1Layout.setHorizontalGroup(
            frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frame1Layout.createSequentialGroup()
                        .addComponent(passwordt, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showb, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(usernamet)
                    .addComponent(loginb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(frame1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(frame1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frame1Layout.setVerticalGroup(
            frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(usernamet, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showb, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(frame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbActionPerformed
        // TODO add your handling code here
        passwordt.setEchoChar((char)0);

    }//GEN-LAST:event_showbActionPerformed

    private void passwordtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_passwordtActionPerformed

    private void passwordtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordtFocusLost
        // TODO add your handling code here:
        if(passwordt.getText().equals(""))
        passwordt.setText("*****");
    }//GEN-LAST:event_passwordtFocusLost

    private void passwordtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordtFocusGained
        // TODO add your handling code here:
        if(passwordt.getText().equals("*****"))
        passwordt.setText("");
    }//GEN-LAST:event_passwordtFocusGained

    private void usernametActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametActionPerformed

    private void usernametFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernametFocusLost
        // TODO add your handling code here:
        if(usernamet.getText().equals(""))
        usernamet.setText("User Name");
    }//GEN-LAST:event_usernametFocusLost

    private void usernametFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernametFocusGained
        // TODO add your handling code here:
        if(usernamet.getText().equals("User Name"))
        usernamet.setText("");
    }//GEN-LAST:event_usernametFocusGained

    private void loginbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbActionPerformed
        // TODO add your handling code here:
    	
        System.out.println("Hello");
        JOptionPane.showMessageDialog(this," correct password");
        
       
       
        try{
      	 Connection Con= DbConnection.GetDbConnection();
      	 JOptionPane.showMessageDialog(this," established");
      	Statement stmt = null;	 stmt = Con.createStatement();

        String s=usernamet.getText();
        JOptionPane.showMessageDialog(null, "you have entered"+s+ "names");
        String s1=passwordt.getText();
        JOptionPane.showMessageDialog(null, "you have entered"+s1+ "names");

  	 String sql = "SELECT sub_id,pass FROM user_cred where sub_id='" +s+"'";
       ResultSet rs = stmt.executeQuery(sql);
       //STEP 5: Extract data from result set
       String ud="o";
       String pd2="i";
       while(rs.next()){
          //Retrieve by column name
      	  ud  = rs.getString("sub_id");
            pd2 = rs.getString("pass");
          

          //Display values
          System.out.println("userid: " + ud);
          System.out.println("passwd: " + pd2);
          
          
       }
       
       
       
       if(pd2.trim().equals(s1))
       {
      	 System.out.println("printing password2 ");
      	 JOptionPane.showMessageDialog(this,"password matches bala");
      	 
      	 this.setVisible(false);
      	 //ColorsFrame1 frame=new ColorsFrame1();
      	//Adminpage aa=new Adminpage();
 		//aa.maing();
      	 String deq=pd2.trim().substring(0,3);
      	 System.out.println("substring is "+deq);
      	 if(deq.equals("pwd")){
      	changePassword p=new changePassword();
      	 p.maing(ud,pd2);
      	 }
      	 else{
      		 
      		 
      		Userpage up=new Userpage();
    		up.maing(ud,pd2);
    		
      		 
      		 
      		 
      		 
      		 
      		 //code for alternative path
      	 }
      	
      	
 	   
 	    
 	    
      	 
      	 }
       
       
       else
       {
      	 System.out.println("password is not matching ");
      	 JOptionPane.showMessageDialog(this,"password not matches bala");
      	 
      	// this.setVisible(false);
      	 //ColorsFrame1 frame=new ColorsFrame1();
      	 
      	 }
                     	       	 
     	        	 
          
      	 
      	 
      	 
      	 
      	 Con.close(); 
       	  }//end try
       catch(SQLException se){
           //Handle errors for JDBC
               se.printStackTrace();
            }
       	 catch(Exception ex)
       	 {
       	 }
        
        
       
        
        
        String uname=usernamet.getText();
        System.out.println("text field data is "+uname);
        
        
        
        
        
        
        
    }//GEN-LAST:event_loginbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	
    	
    	
    	
          
    	try{
         	 Connection Con= DbConnection.GetDbConnection();
         	 JOptionPane.showMessageDialog(this,"admin  established");
         	Statement stmt = null;	 stmt = Con.createStatement();

           String s=usernamet.getText();
           JOptionPane.showMessageDialog(null, "admin you have entered "+s+ "names");
           String s1=passwordt.getText();
           JOptionPane.showMessageDialog(null, "admin you have entered"+s1+ "names");

     	 String sql = "SELECT sub_id,pass FROM admin_cred where sub_id='" +s+"'";
          ResultSet rs = stmt.executeQuery(sql);
          //STEP 5: Extract data from result set
          String ud;
          String pd2="i";
          while(rs.next()){
             //Retrieve by column name
         	  ud  = rs.getString("sub_id");
               pd2 = rs.getString("pass");
             

             //Display values
             System.out.println("userid: " + ud);
             System.out.println("passwd: " + pd2);
             
             
          }
          
          
          
          if(pd2.trim().equals(s1))
          {
         	 System.out.println("admin printing password2 ");
         	 JOptionPane.showMessageDialog(this,"admin password matches bala");
         	 
         	 
         	 this.setVisible(false);
         	 //ColorsFrame1 frame=new ColorsFrame1();
         	 
         	Adminpage aa=new Adminpage();
     		aa.maing();
         	 
         	 }
          
          
          else
          {
         	 System.out.println("password is not matching ");
         	 JOptionPane.showMessageDialog(this,"password not matches bala");
         	 
         	// this.setVisible(false);
         	 //ColorsFrame1 frame=new ColorsFrame1();
         	 
         	 }
                        	       	 
        	        	 
             
         	 
         	 
         	 
         	 
         	 Con.close(); 
          	  }//end try
          catch(SQLException se){
              //Handle errors for JDBC
                  se.printStackTrace();
               }
          	 catch(Exception ex)
          	 {
          	 }
           
             
          
          
          
    	
    	
    	
    	
    	
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void maing() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mains().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame frame1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginb;
    private javax.swing.JPasswordField passwordt;
    private javax.swing.JButton showb;
    private javax.swing.JTextField usernamet;
    // End of variables declaration//GEN-END:variables
}
